#!/usr/bin/python
import os

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

# addidional environ parameters
os.environ.update({'CDN_PREFIX': '/static',
                   'TEMPLATES_AUTORELOAD': '0',
                   'OAUTH_BASE': 'https://%s/login' % os.environ['OPENSHIFT_APP_DNS'],
                   'DBNAME': os.environ['OPENSHIFT_APP_NAME']})

from myflick.app import application
