{% extends 'default.phtml' %}
{% import 'macros.phtml' as macros %}

{% block scripts %}
  {{ super() }}
  <script>var user_id={{user.id}};</script>
{% endblock %}

{% block main_body %}
  <div>your watchlist: </div>

  {% for m in user.watchlist %}
    <a href="/movie/{{m.id}}-_" >{{m.title}}</a>
      {% if m.id in avg_rating %}
        average: {{macros.stars(avg_rating[m.id])}}
      {% endif %}<br/>
  {% endfor %}
{% endblock %}
