{% extends 'base.phtml' %}
{% import 'macros.phtml' as macros %}

{% block title %}My Flicks{% endblock %}

{% block scripts %}
  <script>var cdn="{{cdn}}";</script>
  {{super() }}

  <link href="{{cdn}}/js/rateit/rateit.css" media="all" rel="stylesheet" type="text/css" />
  <script src="{{cdn}}/js/rateit/jquery.rateit.min.js" ></script>

  <script>
    $(document).ready(function(){
      $(".button").button();
      $(".buttonset").buttonset();
      $("input[type=submit]").button();
    });

    function getCachedJson(url, callback) {
      var body = $('body');
      var cache = body.data(url);
      if (cache) {
        callback(cache);
      } else {
        $.getJSON(url, {}, function(json) {
          body.data(url, json);
          callback(json);
        });
      }
    }
  </script>
{% endblock %}

{% block header %}
  <div id="main_menu" class="span-18 buttonset">
  {% block menu %}
    <a href="/" class="button" >My Flicks</a>
  {% endblock %}
  </div>

  <div class="span-5" >
  {% block user_box %}
    {% if user is none %}
    <div>
      Login: <br/>
      <a href="/login/g/{{path[1:]}}" title="google"><img src="{{cdn}}/img/g-icon.png" /></a>
      <a href="/login/twitter/{{path[1:]}}" title="twitter"><img src="{{cdn}}/img/twitter-icon.png" /></a>
      <a href="/login/fb/{{path[1:]}}" title="facebook"><img src="{{cdn}}/img/fb-icon.png" /></a>
    </div>
    {% else %}
      <div style="margin-top: 10px;">
        welcome, {{ user.fullname }}
        <div style="float:right;" class="buttonset">
          <a href="/login/logout/{{path[1:]}}" class="button">Logout</a>
        </div>
      </div>
    {% endif %}
  {% endblock %}
  </div>
{% endblock %}

{% block right_col %}
  {% block last_rated %}
  <div class="span-6" >
    <h4>Last rated</h4>
    {% for user, movie_id, movie_title, rating in last_rated %}
    <div style="padding:3px; {% if loop.index % 2 == 1 %} background-color: #d7ebf9; {% endif %}" >
      <a href="/user/{{user.id~'-'~user.alias_repr}}" >{{user.alias|e}}</a>
      rated<br/> <a href="/movie/{{movie_id~'-'~url_quote(movie_title)}}">{{movie_title|e}}</a>
      {{macros.stars(rating)}}
    </div>
    {% endfor %}
  </div>
  {% endblock %}

{% endblock %}
