{% extends 'base.phtml' %}

{% block title %}My Flick{% endblock %}

{% block scripts %}
  <script>var cdn="{{cdn}}";</script>
  {{super() }}
  <script>
    $(document).ready(function(){
      $(".button").button();
      $(".buttonset").buttonset();
      $("input[type=submit]").button();
    });

    function getCachedJson(url, callback) {
      var body = $('body');
      var cache = body.data(url);
      if (cache) {
        callback(cache);
      } else {
        $.getJSON(url, {}, function(json) {
          body.data(url, json);
          callback(json);
        });
      }
    }
  </script>
{% endblock %}

{% block header %}
  <div id="main_menu" >
  {% block menu %}
    <a href="/" class="button" >Home</a>
  {% endblock %}
  </div>
{% endblock %}

{% block right_col %}
  {% block user_box %}

    {% if user is none %}
    <div>
      Login: <br/>
      <a href="/login/g/{{path[1:]}}" title="google"><img src="{{cdn}}/img/g-icon.png" /></a>
    </div>
    {% else %}
      <div style="margin-top: 30px;">
        welcome, {{ user.fullname }}
        <div style="float:right;">
          <a href="/login/logout/{{path[1:]}}" class="button">Logout</a>
        </div>
      </div>
    {% endif %}
  {% endblock %}

  {% block last_rated %}
  <div class="span-6" >
    <h4>Last rated</h4>
    {% for user, movie_id, movie_title, rating in last_rated %}
    <div {% if loop.index % 2 == 1 %} style="background-color: #d7ebf9;" {% endif %} >
      <a href="/user/{{user.id~'-'~user.alias_repr}}" >{{user.alias|e}}</a>
      gave <a href="/movie/{{movie_id~'-'~url_quote(movie_title)}}">{{movie_title|e}}</a>
      <b>{{rating*0.5}}</b> stars
    </div>
    {% endfor %}
  </div>
  {% endblock %}

{% endblock %}
