{% extends 'default.phtml' %}
{% import 'macros.phtml' as macros %}

{% block scripts %}
  {{ super() }}
  <script src="{{cdn}}/js/rateit/jquery.rateit.min.js" ></script>
  <link href="{{cdn}}/js/rateit/rateit.css" media="all" rel="stylesheet" type="text/css" />
{% endblock %}

{% block head_rest %}
  <meta name="google-site-verification" content="" />
{% endblock %}

{% block main_body %}
	<div id="search_box" >
	  Search:
      <input type="input" name="q" value="{{q|e}}" />
	</div>

   <div id="results" >
   </div>

   <div id='partial' >
   </div>

   <script>
var search_box = $("div#search_box input[name=q]");
var results_div = $("div#results");

search_box.keyup(function(event){
  var q = search_box.val();
  if (q.length > 2) {
    getCachedJson('/autocomplete/movie/'+encodeURIComponent(q), function(json){
      var html = '';
      var ratings = {};
      $.each(json, function(id, item) {
        html = html + '<div class="movie" id="movie_'+item[0]+'" ><span class="span-8"><a class="title" href="/movie/' +
             item[0] + '-_" >' +
             item[1] + '</a></span><span class="rateit" ></span></div>';
        ratings[item[0]] = item[3];
      });

      results_div.html(html);
      $("span.rateit").rateit();
      $.each($("div.movie"), function(_, div){
        var movie_id = $(div).attr('id').replace('movie_','');
        $(div).find("span.rateit").rateit('value', ratings[movie_id]*.5);
      });

      $('div.movie :even').css('background-color', '#d7ebf9');
    });
  } else {
    results_div.html('');
  }
});

$("span.rateit").live("rated", function() {
  var rater = $(this);
  var movie_id = rater.parents("div.movie").attr('id').replace('movie_','');
  var rating = rater.rateit('value')*2;
  $.post('/user/rate', {movie_id: movie_id, rating: rating}, function(response){});

});

$("span.rateit").live("reset", function() {
  //console.debug(this); // TODO
});

var movie_partials = {};
$("div.movie").live("mouseenter", function() {
  var movie_id = $(this).attr("id").replace('movie_','');

  var partial = movie_partials[movie_id];
  if (partial) {
      $("div#partial").html(partial);

  } else {
    $.get('/movie/partial/'+movie_id, {}, function(response) {
      $("div#partial").html(response);
      movie_partials[movie_id] = response;
    });
  }

});

   </script>
{% endblock %}
