{% extends 'default.phtml' %}
{% import 'macros.phtml' as macros %}

{% block scripts %}
  {{ super() }}
  {% if user %}
    <script src="{{cdn}}/js/rateit/jquery.rateit.min.js" ></script>
    <link href="{{cdn}}/js/rateit/rateit.css" media="all" rel="stylesheet" type="text/css" />
    <script>var user_id={{user.id}};</script>
  {% endif %}
  <script src="{{cdn}}/js/index.js" ></script>
  <style>
    div.movie {margin-top:7px; margin-bottom:7px;}
  </style>
{% endblock %}

{% block head_rest %}
  <meta name="google-site-verification" content="" />
{% endblock %}

{% block main_body %}
	<div id="search_box" class="span-17" >
	  Search:
      <input type="input" name="q" value="{{q|e}}" />
	</div>

   <div id="results" class="span-17">
   </div>

   <div id="not-found" class="span-17">
     <div class="small prepend-14" ><a href="/movie/missing" >not found?</a></div>
   </div>

   <div id='partial' class="span-17" >
   </div>

   <div id='strips' class="span-17" >
     <table>
       <tr>
         <td colspan=5 style="padding-left:100px;"><h4>Last Rated</h4></td>
       </tr>
       <tr>
         {% for user, movie_id, movie_title, rating in last_rated %}
           <td>
             <b>{{movie_title|e}}</b> ({{movies[movie_id].year}}) <br/>
             <a href="/movie/{{movie_id~'-'~url_quote(movie_title)}}" >
               <img src="{{movies[movie_id].get_image()}}" width="127" /></a> <br/>
             <b>{{(rating*0.5) ~'</b> by '~ user.alias|e }}
           </td>
         {% endfor %}
       </tr>
       <tr>
         <td colspan=5 style="padding-left:100px;"><h4>Top Rated</h4></td>
       </tr>
       <tr>
         {% for m, avg_ in top_rated %}
           <td>
             <b>{{m.title|e}}</b> ({{m.year}}) <br>
             <a href="/movie/{{m.id~'-'~url_quote(m.title)}}" >
               <img src="{{m.get_image()}}" width="127" /></a> <br/>
             <b>{{ '%.2f' % (avg_ / 2) }}</b></td>
         {% endfor %}
       </tr>
     </table>
   </div>
{% endblock %}
