{% macro search_box(q, tr) %}
<div id="search_box" >
  <form action="/search" method="post" >
    <input type="input" name="q" value="{{q|e}}" /> 
    <input type="submit" value="Search" />
  </form>
</div>
{% endmacro %}

{% macro movie_widget(movie, meta) %}
<div>
{% if meta %}
  <h3>{{meta['Title'] ~' ('~ meta['Year'] ~')'}}</h3>
  <div>Director: {{meta['Director']}}, Screenwriter: {{meta['Writer']}}</div>
  <div>Actors: {{meta['Actors']}}</div>
{% else %}
  <h3>{{movie.title ~' ('~ movie.year ~')'}}</h3>
{% endif %}
  <div>
    <img width=300 src="{{movie.get_image()}}" />
  </div>
</div>
{% endmacro %}
