{% extends 'default.phtml' %}
{% import 'macros.phtml' as macros %}

{% block title %}{{movie.title|e ~' ('~movie.year~') @ '~ super()}}{% endblock %}

{% block scripts %}
  {{ super() }}
  {% if user %}
    <script src="{{cdn}}/js/rateit/jquery.rateit.min.js" ></script>
    <link href="{{cdn}}/js/rateit/rateit.css" media="all" rel="stylesheet" type="text/css" />
    <script>var user_id={{user.id}};</script>
  {% endif %}
{% endblock %}

{% block main_body %}
  <div class="span-8" >
    {{ macros.movie_widget(movie, meta) }}
  </div>

  <div class="span-8" style="margin-top: 45px;">
    {% if user %}
    <div class="movie" id="movie_{{movie.id}}" >
      you rate:<span class="rateit" ></span>
    </div>
    {% endif %}

    {% if avg_rating %}
      <h5>Average rating</h5>
        <b>{{avg_rating}}</b> stars
      <h5>Last ratings</h5>
      {% for rating, user in last_ratings %}
        <a href="/user/{{user.id~'-'~user.alias_repr}}" >{{user.alias|e}}</a> {{macros.stars(rating)}} <br/>
      {% endfor %}
    {% endif %}
  </div>

{% if user %}
  <script >
  var rater = $("span.rateit");
  var movie_id = {{movie.id}};
  rater.rateit();

    {% if rating %}
      rater.rateit('value', {{rating.rating*0.5}});
    {% endif %}

    rater.live("rated", function() {
      var rating = rater.rateit('value')*2;
      $.post('/user/rate', {movie_id: movie_id, rating: rating}, function(response){});
    });

    rater.live("reset", function() {
      $.post('/user/rate', {movie_id: movie_id, rating: 0}, function(response){});
    });

  </script >
{% endif %}

{% endblock %}
