{% extends 'default.phtml' %}
{% import 'macros.phtml' as macros %}

{% block main_body %}
  <div>
    User:
    <h4>{{user_.alias|e}}</h4>
    <div class="span-17 last" >
      <a href="#" id="last_first" >new ratings first</a> |
      <a href="#" id="best_first" >high ratings first</a> |
      <a href="#" id="watchlist" >watchlist</a>
    </div> <br/> <br/>

    <div class="span-17 last" id="last_first_">
      {% for movie, rating in ratings1 %}
      <div>{{macros.stars(rating)}}
           <a href="/movie/{{movie.id~'-'~url_quote(movie.title)}}">
           {{movie.title|e}}</a></div>
      {% endfor %}
    </div>

    <div class="span-17 last hidden" id="best_first_">
      {% for movie, rating in ratings2 %}
      <div>{{macros.stars(rating)}}
           <a href="/movie/{{movie.id~'-'~url_quote(movie.title)}}">
           {{movie.title|e}}</a></div>
      {% endfor %}
    </div>

    <div class="span-17 last hidden" id="watchlist_" >
      {% for m in watchlist|sort %}
      <div><a href="/movie/{{m.id~'-'~url_quote(m.title)}}">
           {{m.title|e}}</a></div>
      {% endfor %}
    </div>

    <script>
    $("a#last_first").click(function(){
      $("div#last_first_").show();
      $("div#best_first_").hide();
      $("div#watchlist_").hide();
      return false;
    });
    $("a#best_first").click(function(){
      $("div#best_first_").show();
      $("div#last_first_").hide();
      $("div#watchlist_").hide();
      return false;
    });
    $("a#watchlist").click(function(){
      $("div#best_first_").hide();
      $("div#last_first_").hide();
      $("div#watchlist_").show();
      return false;
    });

    </script>

  </div>
{% endblock %}
